// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: serviceDefinition/market.proto

package serviceDefinition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVegetableNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVegetableNamesRequest) Reset() {
	*x = GetVegetableNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVegetableNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVegetableNamesRequest) ProtoMessage() {}

func (x *GetVegetableNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVegetableNamesRequest.ProtoReflect.Descriptor instead.
func (*GetVegetableNamesRequest) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{0}
}

type GetVegetableNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *GetVegetableNamesResponse) Reset() {
	*x = GetVegetableNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVegetableNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVegetableNamesResponse) ProtoMessage() {}

func (x *GetVegetableNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVegetableNamesResponse.ProtoReflect.Descriptor instead.
func (*GetVegetableNamesResponse) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetVegetableNamesResponse) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

type VegetableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price  float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Amount float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *VegetableInfo) Reset() {
	*x = VegetableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VegetableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VegetableInfo) ProtoMessage() {}

func (x *VegetableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VegetableInfo.ProtoReflect.Descriptor instead.
func (*VegetableInfo) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{2}
}

func (x *VegetableInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VegetableInfo) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *VegetableInfo) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Inventory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VegiEntry map[string]*VegetableInfo `protobuf:"bytes,1,rep,name=vegiEntry,proto3" json:"vegiEntry,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{3}
}

func (x *Inventory) GetVegiEntry() map[string]*VegetableInfo {
	if x != nil {
		return x.VegiEntry
	}
	return nil
}

type GetPricePerUnitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPricePerUnitRequest) Reset() {
	*x = GetPricePerUnitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPricePerUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricePerUnitRequest) ProtoMessage() {}

func (x *GetPricePerUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricePerUnitRequest.ProtoReflect.Descriptor instead.
func (*GetPricePerUnitRequest) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{4}
}

func (x *GetPricePerUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPricePerUnitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GetPricePerUnitResponse) Reset() {
	*x = GetPricePerUnitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPricePerUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricePerUnitResponse) ProtoMessage() {}

func (x *GetPricePerUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricePerUnitResponse.ProtoReflect.Descriptor instead.
func (*GetPricePerUnitResponse) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{5}
}

func (x *GetPricePerUnitResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetAmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAmountRequest) Reset() {
	*x = GetAmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmountRequest) ProtoMessage() {}

func (x *GetAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmountRequest.ProtoReflect.Descriptor instead.
func (*GetAmountRequest) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{6}
}

func (x *GetAmountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float32 `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetAmountResponse) Reset() {
	*x = GetAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAmountResponse) ProtoMessage() {}

func (x *GetAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAmountResponse.ProtoReflect.Descriptor instead.
func (*GetAmountResponse) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{7}
}

func (x *GetAmountResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddUpdateVegetableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddUpdateVegetableResponse) Reset() {
	*x = AddUpdateVegetableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceDefinition_market_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUpdateVegetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUpdateVegetableResponse) ProtoMessage() {}

func (x *AddUpdateVegetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceDefinition_market_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUpdateVegetableResponse.ProtoReflect.Descriptor instead.
func (*AddUpdateVegetableResponse) Descriptor() ([]byte, []int) {
	return file_serviceDefinition_market_proto_rawDescGZIP(), []int{8}
}

func (x *AddUpdateVegetableResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_serviceDefinition_market_proto protoreflect.FileDescriptor

var file_serviceDefinition_market_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x56, 0x65, 0x67, 0x65, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x51, 0x0a, 0x0d, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb8, 0x01, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x4a, 0x0a, 0x09, 0x76, 0x65, 0x67, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x56, 0x65, 0x67, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x09, 0x76, 0x65, 0x67, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x5f,
	0x0a, 0x0e, 0x56, 0x65, 0x67, 0x69, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x55, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x26,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x97, 0x04, 0x0a, 0x0a,
	0x56, 0x65, 0x67, 0x69, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x72, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50,
	0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x55, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x56,
	0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65,
	0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x2e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x41, 0x64, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a,
	0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x2e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x67, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x22, 0x5a, 0x20, 0x76, 0x65, 0x67, 0x69, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_serviceDefinition_market_proto_rawDescOnce sync.Once
	file_serviceDefinition_market_proto_rawDescData = file_serviceDefinition_market_proto_rawDesc
)

func file_serviceDefinition_market_proto_rawDescGZIP() []byte {
	file_serviceDefinition_market_proto_rawDescOnce.Do(func() {
		file_serviceDefinition_market_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviceDefinition_market_proto_rawDescData)
	})
	return file_serviceDefinition_market_proto_rawDescData
}

var file_serviceDefinition_market_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_serviceDefinition_market_proto_goTypes = []interface{}{
	(*GetVegetableNamesRequest)(nil),   // 0: service.definition.GetVegetableNamesRequest
	(*GetVegetableNamesResponse)(nil),  // 1: service.definition.GetVegetableNamesResponse
	(*VegetableInfo)(nil),              // 2: service.definition.VegetableInfo
	(*Inventory)(nil),                  // 3: service.definition.Inventory
	(*GetPricePerUnitRequest)(nil),     // 4: service.definition.GetPricePerUnitRequest
	(*GetPricePerUnitResponse)(nil),    // 5: service.definition.GetPricePerUnitResponse
	(*GetAmountRequest)(nil),           // 6: service.definition.GetAmountRequest
	(*GetAmountResponse)(nil),          // 7: service.definition.GetAmountResponse
	(*AddUpdateVegetableResponse)(nil), // 8: service.definition.AddUpdateVegetableResponse
	nil,                                // 9: service.definition.Inventory.VegiEntryEntry
}
var file_serviceDefinition_market_proto_depIdxs = []int32{
	9, // 0: service.definition.Inventory.vegiEntry:type_name -> service.definition.Inventory.VegiEntryEntry
	2, // 1: service.definition.Inventory.VegiEntryEntry.value:type_name -> service.definition.VegetableInfo
	0, // 2: service.definition.VegiMarket.GetVegetableNames:input_type -> service.definition.GetVegetableNamesRequest
	4, // 3: service.definition.VegiMarket.GetPricePerUnit:input_type -> service.definition.GetPricePerUnitRequest
	6, // 4: service.definition.VegiMarket.GetAmount:input_type -> service.definition.GetAmountRequest
	2, // 5: service.definition.VegiMarket.AddVegetable:input_type -> service.definition.VegetableInfo
	2, // 6: service.definition.VegiMarket.UpdateVegetable:input_type -> service.definition.VegetableInfo
	1, // 7: service.definition.VegiMarket.GetVegetableNames:output_type -> service.definition.GetVegetableNamesResponse
	5, // 8: service.definition.VegiMarket.GetPricePerUnit:output_type -> service.definition.GetPricePerUnitResponse
	7, // 9: service.definition.VegiMarket.GetAmount:output_type -> service.definition.GetAmountResponse
	8, // 10: service.definition.VegiMarket.AddVegetable:output_type -> service.definition.AddUpdateVegetableResponse
	8, // 11: service.definition.VegiMarket.UpdateVegetable:output_type -> service.definition.AddUpdateVegetableResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_serviceDefinition_market_proto_init() }
func file_serviceDefinition_market_proto_init() {
	if File_serviceDefinition_market_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serviceDefinition_market_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVegetableNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVegetableNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VegetableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inventory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPricePerUnitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPricePerUnitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceDefinition_market_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUpdateVegetableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviceDefinition_market_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviceDefinition_market_proto_goTypes,
		DependencyIndexes: file_serviceDefinition_market_proto_depIdxs,
		MessageInfos:      file_serviceDefinition_market_proto_msgTypes,
	}.Build()
	File_serviceDefinition_market_proto = out.File
	file_serviceDefinition_market_proto_rawDesc = nil
	file_serviceDefinition_market_proto_goTypes = nil
	file_serviceDefinition_market_proto_depIdxs = nil
}
